import { KitSolanaAccountsAdapter } from './src/adapters/solana/kit-solana-accounts.adapter.js';
import { FetchHttpJsonAdapter } from './src/adapters/http/fetch-http-json.adapter.js';
import { MeteoraDammV2PriceFeed } from './src/core/pricing/meteora-damm-v2-price-feed.js';
import { PoolDirectory } from './src/core/pricing/pool-directory.js';
import { UsdQuotes } from './src/core/pricing/usd-quotes.js';
const acc = new KitSolanaAccountsAdapter(process.env.SOLANA_RPC_HTTP!, process.env.SOLANA_RPC_WSS!, () => undefined);
const http = new FetchHttpJsonAdapter();
const q = new UsdQuotes(acc, http, 'https://lite-api.jup.ag/price/v3', 2000, () => undefined); await q.start();
const f = new MeteoraDammV2PriceFeed(acc, new PoolDirectory(http), q, () => undefined);
let last = '';
await f.watch('DMPAgkCZmz4TZKJrbV11KGvHZUnCqc8uvnLL62SapDZJ', (t) => { last = `${t.priceUsd.toExponential(4)} (VBUCKS $${q.usd('At541hRZhK9LWKj9w2dqN2wCdpFyZgRa1Un2yG7xa43m')?.toExponential(4)})`; });
const iv = setInterval(() => console.log(new Date().toISOString().slice(11, 19), 'ours', last), 2000);
setTimeout(() => { clearInterval(iv); process.exit(0); }, 16000);
