import { KitSolanaAccountsAdapter } from './src/adapters/solana/kit-solana-accounts.adapter.js';
import { FetchHttpJsonAdapter } from './src/adapters/http/fetch-http-json.adapter.js';
import { CompositePriceFeed } from './src/core/pricing/composite-price-feed.js';
import { MeteoraDammV2PriceFeed } from './src/core/pricing/meteora-damm-v2-price-feed.js';
import { PoolDirectory } from './src/core/pricing/pool-directory.js';
import { PumpPriceFeed } from './src/core/pricing/pump-price-feed.js';
import { RaydiumCpmmPriceFeed } from './src/core/pricing/raydium-cpmm-price-feed.js';
import { UsdQuotes } from './src/core/pricing/usd-quotes.js';
const acc = new KitSolanaAccountsAdapter(process.env.SOLANA_RPC_HTTP!, process.env.SOLANA_RPC_WSS!, () => undefined);
const http = new FetchHttpJsonAdapter();
const dir = new PoolDirectory(http);
const q = new UsdQuotes(acc, http, 'https://lite-api.jup.ag/price/v3', 5000, (e) => console.error('q', e));
await q.start();
const onchain = new CompositePriceFeed([new PumpPriceFeed(acc, () => undefined), new RaydiumCpmmPriceFeed(acc, dir, q, () => undefined), new MeteoraDammV2PriceFeed(acc, dir, q, () => undefined)]);
await onchain.start();
q.setOnchainFeed(onchain);
let last = '';
await onchain.watch('DMPAgkCZmz4TZKJrbV11KGvHZUnCqc8uvnLL62SapDZJ', (t) => { last = `${t.source} $${t.priceUsd.toExponential(4)} VBUCKS=$${q.usd('At541hRZhK9LWKj9w2dqN2wCdpFyZgRa1Un2yG7xa43m')?.toExponential(4)}`; });
const iv = setInterval(() => console.log(new Date().toISOString().slice(11, 19), last), 2000);
setTimeout(() => { clearInterval(iv); process.exit(0); }, 12000);
